## Regions of gui/keys.png, one per input prompt — GENERATED by tools/gen_key_icons.py.
## Do not hand-edit: change the tables in that script and re-run it.
##
## Names read as <device>_<key>: `key_*` for the keyboard, `mouse_*`, `pad_*` for a
## controller. Ask for one with texture(), which caches the AtlasTexture, and let the
## Control size itself to the region — these are 1:1 art and must never be scaled.
class_name KeyIcons

const SHEET := preload("res://gui/keys.png")

const REGIONS := {
	&"key_a": Rect2(0, 0, 8, 8),
	&"key_b": Rect2(8, 0, 8, 8),
	&"key_c": Rect2(16, 0, 8, 8),
	&"key_d": Rect2(24, 0, 8, 8),
	&"key_e": Rect2(32, 0, 8, 8),
	&"key_f": Rect2(40, 0, 8, 8),
	&"key_g": Rect2(48, 0, 8, 8),
	&"key_h": Rect2(56, 0, 8, 8),
	&"key_i": Rect2(64, 0, 8, 8),
	&"key_j": Rect2(72, 0, 8, 8),
	&"key_k": Rect2(80, 0, 8, 8),
	&"key_l": Rect2(88, 0, 8, 8),
	&"key_m": Rect2(96, 0, 8, 8),
	&"key_n": Rect2(104, 0, 8, 8),
	&"key_o": Rect2(112, 0, 8, 8),
	&"key_p": Rect2(120, 0, 8, 8),
	&"key_q": Rect2(0, 8, 8, 8),
	&"key_r": Rect2(8, 8, 8, 8),
	&"key_s": Rect2(16, 8, 8, 8),
	&"key_t": Rect2(24, 8, 8, 8),
	&"key_u": Rect2(32, 8, 8, 8),
	&"key_v": Rect2(40, 8, 8, 8),
	&"key_w": Rect2(48, 8, 8, 8),
	&"key_x": Rect2(56, 8, 8, 8),
	&"key_y": Rect2(64, 8, 8, 8),
	&"key_z": Rect2(72, 8, 8, 8),
	&"key_0": Rect2(0, 16, 8, 8),
	&"key_1": Rect2(8, 16, 8, 8),
	&"key_2": Rect2(16, 16, 8, 8),
	&"key_3": Rect2(24, 16, 8, 8),
	&"key_4": Rect2(32, 16, 8, 8),
	&"key_5": Rect2(40, 16, 8, 8),
	&"key_6": Rect2(48, 16, 8, 8),
	&"key_7": Rect2(56, 16, 8, 8),
	&"key_8": Rect2(64, 16, 8, 8),
	&"key_9": Rect2(72, 16, 8, 8),
	&"key_plus": Rect2(80, 16, 8, 8),
	&"key_minus": Rect2(88, 16, 8, 8),
	&"key_equals": Rect2(96, 16, 8, 8),
	&"key_lbracket": Rect2(104, 16, 8, 8),
	&"key_rbracket": Rect2(112, 16, 8, 8),
	&"key_backquote": Rect2(120, 16, 8, 8),
	&"key_up": Rect2(0, 24, 8, 8),
	&"key_down": Rect2(8, 24, 8, 8),
	&"key_left": Rect2(16, 24, 8, 8),
	&"key_right": Rect2(24, 24, 8, 8),
	&"key_esc": Rect2(32, 24, 16, 8),
	&"key_tab": Rect2(48, 24, 16, 8),
	&"key_alt": Rect2(64, 24, 16, 8),
	&"key_del": Rect2(80, 24, 16, 8),
	&"key_space": Rect2(0, 32, 24, 8),
	&"key_enter": Rect2(24, 32, 24, 8),
	&"key_shift": Rect2(48, 32, 24, 8),
	&"key_ctrl": Rect2(72, 32, 24, 8),
	&"key_bksp": Rect2(96, 32, 24, 8),
	&"key_f1": Rect2(0, 40, 16, 8),
	&"key_f2": Rect2(16, 40, 16, 8),
	&"key_f3": Rect2(32, 40, 16, 8),
	&"key_f4": Rect2(48, 40, 16, 8),
	&"key_f5": Rect2(64, 40, 16, 8),
	&"key_f6": Rect2(80, 40, 16, 8),
	&"key_f7": Rect2(96, 40, 16, 8),
	&"key_f8": Rect2(112, 40, 16, 8),
	&"key_f9": Rect2(0, 48, 16, 8),
	&"key_f10": Rect2(16, 48, 16, 8),
	&"key_f11": Rect2(32, 48, 16, 8),
	&"key_f12": Rect2(48, 48, 16, 8),
	&"mouse": Rect2(0, 56, 8, 8),
	&"mouse_left": Rect2(8, 56, 8, 8),
	&"mouse_middle": Rect2(16, 56, 8, 8),
	&"mouse_right": Rect2(24, 56, 8, 8),
	&"mouse_wheel": Rect2(32, 56, 16, 8),
	&"mouse_wheel_up": Rect2(48, 56, 16, 8),
	&"mouse_wheel_down": Rect2(64, 56, 16, 8),
	&"mouse_drag": Rect2(80, 56, 16, 8),
	&"pad_a": Rect2(0, 64, 8, 8),
	&"pad_b": Rect2(8, 64, 8, 8),
	&"pad_x": Rect2(16, 64, 8, 8),
	&"pad_y": Rect2(24, 64, 8, 8),
	&"pad_l1": Rect2(32, 64, 16, 8),
	&"pad_r1": Rect2(48, 64, 16, 8),
	&"pad_l2": Rect2(64, 64, 16, 8),
	&"pad_r2": Rect2(80, 64, 16, 8),
	&"pad_start": Rect2(96, 64, 24, 8),
	&"pad_back": Rect2(0, 72, 24, 8),
	&"pad_dpad": Rect2(0, 80, 8, 8),
	&"pad_dpad_up": Rect2(8, 80, 8, 8),
	&"pad_dpad_down": Rect2(16, 80, 8, 8),
	&"pad_dpad_left": Rect2(24, 80, 8, 8),
	&"pad_dpad_right": Rect2(32, 80, 8, 8),
	&"pad_dpad_lr": Rect2(40, 80, 8, 8),
	&"pad_dpad_ud": Rect2(48, 80, 8, 8),
	&"pad_stick_l": Rect2(0, 88, 12, 8),
	&"pad_stick_r": Rect2(12, 88, 12, 8),
	&"pad_stick_l3": Rect2(24, 88, 12, 8),
	&"pad_stick_r3": Rect2(36, 88, 12, 8),
	&"chord": Rect2(0, 96, 8, 8),
	&"alt_slash": Rect2(8, 96, 8, 8),
	&"hud_controls": Rect2(16, 96, 8, 8),
}

static var _cache: Dictionary = {}

## The AtlasTexture for `name`, or null if nothing is named that (a typo'd prompt should
## leave a hole, not crash the HUD).
static func texture(name: StringName) -> AtlasTexture:
	if _cache.has(name):
		return _cache[name]
	if not REGIONS.has(name):
		push_warning("KeyIcons: no icon named '%s'" % name)
		return null
	var tex := AtlasTexture.new()
	tex.atlas = SHEET
	tex.region = REGIONS[name]
	_cache[name] = tex
	return tex
