#!/usr/bin/env python3
"""Join the design words to the game's numbers, and render every view of them.

    design/data/*.yaml   (words, judgement calls)
                        \\
                         +--> build.py --> design/docs/data.json   THE dataset
                        /                  design/docs/data.js     the same, for file://
    game/**.tres,.tscn   (every number)     design/docs/*.md       injected regions
      via extract.py                        design/docs/*.html     the browsable views

One dataset, one command. `data.json` is the contract: graphs, notebooks, balance
tools and the four HTML pages all read it and nothing re-derives a number from
the yaml. Each Markdown doc keeps a hand-written preamble and an "ideas" tail;
only the region between the GENERATED markers is machine-owned.

Usage:
    python3 design/tools/build.py [--check]

--check exits non-zero if any output is stale or any id fails to resolve, and
writes nothing. That is what the pre-commit hook runs.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape

import extract

ROOT = Path(__file__).resolve().parents[1]          # design/
DATA = ROOT / "data"
DOCS = ROOT / "docs"
TEMPLATES = Path(__file__).resolve().parent

BEGIN = "<!-- BEGIN GENERATED CATALOGUE -->"
END = "<!-- END GENERATED CATALOGUE -->"

GEN_NOTE = (
    "<!-- Generated by design/tools/build.py from design/data/ + the game's .tres "
    "— do not edit by hand. -->"
)

# The player's authored base stats, so a scaled number can be shown as a number.
BASE_STATS = {"skill": 25, "speed": 80, "defence": 0}
PX_PER_TILE = extract.PX_PER_TILE

RARITY_ORDER = {"common": 0, "rare": 1, "boss": 2}


def load(name: str) -> dict:
    with (DATA / name).open() as fh:
        return yaml.safe_load(fh)


def _clean(text: str) -> str:
    """Collapse a folded-scalar description to a single paragraph line."""
    return " ".join((text or "").split())


def _first_paragraph(text: str) -> str:
    """First paragraph of a literal markdown block, collapsed to one line.

    Enemy descriptions can carry a trailing bullet list (e.g. a boss's phases);
    the card view wants just the lead blurb, the full detail lives in the doc.
    """
    return _clean((text or "").strip().split("\n\n", 1)[0])


# --- the join ---------------------------------------------------------------

def _hold(tiers: list[dict]) -> str:
    """How the spell holds you — derived, not authored (see docs/spells.md)."""
    if any(t.get("channeled") for t in tiers):
        return "channeled"
    if any(t.get("cast_time") for t in tiers):
        return "charged"
    return "no"


def _scalings(tier: dict) -> list[str]:
    """Which stats this tier's power actually grows with."""
    amount = tier.get("amount") or (tier.get("minion_cast") or {}).get("amount") or {}
    return [k for k in ("skill", "speed", "defence") if amount.get(k)]


def _damage(tier: dict, stats: dict = BASE_STATS) -> float:
    """ScalingProfile.compute() — the one damage formula, mirrored for display."""
    amount = tier.get("amount") or {}
    return (
        amount.get("base", 0)
        + amount.get("skill", 0) * stats["skill"]
        + amount.get("speed", 0) * stats["speed"]
        + amount.get("defence", 0) * stats["defence"]
    )


def _attack_name(enemy_id: str, cast: str) -> str:
    """`gnarlking_brood` -> brood, `fae_rings_spell` -> rings, `wasp_spell` -> attack."""
    stem = cast.removeprefix(f"{enemy_id}_").removesuffix("_spell").removesuffix("spell")
    return stem.strip("_") or "attack"


def _icon_url(icon: dict | None) -> dict | None:
    """A game res:// icon -> a path the docs pages can actually load."""
    if not icon or not icon.get("path"):
        return None
    rel = icon["path"].replace("res://", "")
    return {"url": f"../../game/{rel}", "region": icon.get("region")}


def join(design: dict, game: dict) -> dict:
    """The one dataset: design words + game numbers, keyed on game ids."""
    spells = []
    for sp in design["spells"]["spells"]:
        tiers = game["spells"][sp["id"]]
        top = tiers[-1]
        spells.append({
            "id": sp["id"],
            "name": sp["name"],
            "category": sp["category"],
            "description": _clean(sp["description"]),
            "per_tier": sp.get("per_tier", ""),
            "kind": top["kind"],
            "hold": _hold(tiers),
            "scaling": _scalings(top) or ["flat"],
            "grants": sorted({k for t in tiers for k in t.get("grants", {})}),
            "tiers": tiers,
        })

    # Which biomes actually spawn each enemy, and which merely plan to.
    membership: dict[str, list[dict]] = {}
    for biome in design["biomes"]["biomes"]:
        shipped = [
            m["enemy"]
            for room in game["biomes"][biome["id"]]["rooms"]
            for var in room["variations"]
            for m in var["members"]
            if m["enemy"]
        ]
        roster = dict.fromkeys(shipped)
        planned = not roster
        for eid in (biome.get("planned_roster") or []) if planned else []:
            roster[eid] = None
        for eid in roster:
            membership.setdefault(eid, []).append(
                {"id": biome["id"], "name": biome["name"], "planned": planned}
            )

    enemies = []
    for e in design["enemies"]["enemies"]:
        g = game["enemies"][e["id"]]
        bases = [a["amount"]["base"] for a in g["attacks"] if (a.get("amount") or {}).get("base")]
        attacks = [{**a, "name": _attack_name(e["id"], a["cast"])} for a in g["attacks"]]
        enemies.append({
            **{k: v for k, v in g.items() if k not in ("icon", "attacks")},
            "attacks": attacks,
            "id": e["id"],
            "difficulty": e["difficulty"],
            "description": e["description"],
            "blurb": _first_paragraph(e["description"]),
            "art": e["art"],
            "casts": e["casts"],
            "notes": e.get("notes", ""),
            "fsm": e["fsm"],
            "icon": _icon_url(g["icon"]),
            "damage_max": max(bases, default=0),
            "damage": "-".join(str(n) for n in sorted({min(bases), max(bases)})) if bases else "",
            "biomes": membership.get(e["id"], []),
        })
    enemies.sort(key=lambda e: (RARITY_ORDER[e["rarity"]], e["id"]))
    by_enemy = {e["id"]: e for e in enemies}

    biomes, rooms = [], []
    for b in design["biomes"]["biomes"]:
        g = game["biomes"][b["id"]]
        roster = [e["id"] for e in enemies
                  if any(m["id"] == b["id"] for m in e["biomes"])]
        biomes.append({
            **{k: v for k, v in g.items() if k != "rooms"},
            "name": b["name"],
            "intro": _clean(b["intro"]),
            "roster": roster,
            "planned": bool(b.get("planned_roster")),
            "room_ids": [r["id"] for r in g["rooms"]],
        })
        for room in g["rooms"]:
            rooms.append({**room, "biome_name": b["name"], "family": g["family"] or b["id"]})

    families = []
    for f in design["biomes"]["families"]:
        members = [b for b in biomes if (b["family"] or b["id"]) == f["id"]]
        families.append({
            **f,
            "intro": _clean(f["intro"]),
            "enemies_intro": _clean(f["enemies_intro"]),
            "biomes": [b["id"] for b in members],
            "roster": list(dict.fromkeys(eid for b in members for eid in b["roster"])),
        })

    return {
        "categories": [
            {"id": c["id"], "name": c["name"], "description": _clean(c["description"])}
            for c in design["spells"]["categories"]
        ],
        "spells": spells,
        "enemies": enemies,
        "families": families,
        "biomes": biomes,
        "rooms": rooms,
        "starter_kit": [
            {"item": stem, "spell": next(
                (s["name"] for s in spells if stem.startswith(s["id"])), stem)}
            for stem in game["starter_kit"]
        ],
        "constants": {"px_per_tile": PX_PER_TILE, "base_stats": BASE_STATS},
        "_by_enemy": by_enemy,       # build-time convenience, stripped before writing
    }


# --- validation -------------------------------------------------------------
# One predicate per way the yaml and the game can disagree. This is what catches
# the drift that used to sit in the docs unnoticed.

def validate(design: dict, game: dict) -> list[str]:
    errors = []

    yaml_spells = {s["id"] for s in design["spells"]["spells"]}
    categories = {c["id"] for c in design["spells"]["categories"]}
    for s in design["spells"]["spells"]:
        if s["id"] not in game["spells"]:
            errors.append(f"spells.yaml: '{s['id']}' ships no .tres under characters/player/spells/")
        if s["category"] not in categories:
            errors.append(f"spells.yaml: '{s['id']}' has unknown category '{s['category']}'")
    for sid in game["spells"]:
        if sid not in yaml_spells:
            errors.append(f"{sid}/ ships .tres files but is not in spells.yaml")

    yaml_enemies = {e["id"] for e in design["enemies"]["enemies"]}
    for e in design["enemies"]["enemies"]:
        if e["id"] not in game["enemies"]:
            errors.append(f"enemies.yaml: '{e['id']}' has no characters/enemies/{e['id']}/")
            continue
        for cast in e["casts"]:
            if cast not in game["spells"]:
                errors.append(f"enemies.yaml: '{e['id']}' casts unknown spell '{cast}'")
        for drop in game["enemies"][e["id"]]["drops"]:
            if drop["spell"] not in game["spells"]:
                errors.append(f"{e['id']}_data.tres drops '{drop['item']}', no such spell")
    for eid in game["enemies"]:
        if eid not in yaml_enemies:
            errors.append(f"{eid}/ ships a scene but is not in enemies.yaml")

    yaml_biomes = {b["id"] for b in design["biomes"]["biomes"]}
    family_ids = {f["id"] for f in design["biomes"]["families"]}
    for b in design["biomes"]["biomes"]:
        if b["id"] not in game["biomes"]:
            errors.append(f"biomes.yaml: '{b['id']}' has no BiomeDef in world_content/")
            continue
        family = game["biomes"][b["id"]]["family"] or b["id"]
        if family not in family_ids:
            errors.append(f"biomes.yaml: '{b['id']}' is in family '{family}', which has no entry")
        spawns = any(m["enemy"]
                     for r in game["biomes"][b["id"]]["rooms"]
                     for v in r["variations"] for m in v["members"])
        if spawns and b.get("planned_roster"):
            errors.append(f"biomes.yaml: '{b['id']}' spawns enemies, so drop its planned_roster")
        for eid in b.get("planned_roster") or []:
            if eid not in yaml_enemies:
                errors.append(f"biomes.yaml: '{b['id']}' plans unknown enemy '{eid}'")
    for bid in game["biomes"]:
        if bid not in yaml_biomes:
            errors.append(f"world_content: biome '{bid}' is not in biomes.yaml")

    for bid, b in game["biomes"].items():
        for room in b["rooms"]:
            pool = any(m["enemy"] for v in room["variations"] for m in v["members"])
            if pool and room["groups_max"] == 0:
                errors.append(f"{room['id']}: has a spawn pool but a zero group budget")
            if room["groups_max"] and not pool:
                errors.append(f"{room['id']}: budgets {room['groups_max']} groups from an empty pool")
            for var in room["variations"]:
                for m in var["members"]:
                    if m["enemy"] and m["enemy"] not in game["enemies"]:
                        errors.append(f"{room['id']}: spawns unknown enemy '{m['enemy']}'")
    return errors


# --- shared formatting ------------------------------------------------------

def notation(variations: list[dict]) -> str:
    """A room's spawn pool in the docs' notation: `2x hopper + 1x wasp - 3x sproutling`.

    `Nx` count (a range prints `1-2x`), `+` means together in the room, `-`
    separates the variations the generator may roll. An empty pool stays empty:
    a room that spawns nothing says so.
    """
    out = []
    for var in variations:
        parts = []
        for m in var["members"]:
            if not m["enemy"]:
                continue
            count = f"{m['min']}" if m["min"] == m["max"] else f"{m['min']}-{m['max']}"
            parts.append(f"{count}x {m['enemy']}")
        if parts:
            out.append(" + ".join(parts))
    return " - ".join(out) if out else "*(empty)*"


def burst(tier: dict) -> str:
    """A cast's shot pattern in one phrase."""
    shots = tier.get("shots")
    if not shots:
        return ""
    text = shots["pattern"].replace("Pattern", "")
    if shots["per_shot"] > 1:
        text += f" x{shots['per_shot']}"
    if shots["count"] > 1:
        text += f", {shots['count']} @ {shots['interval']}s"
    return text


def extras(tier: dict) -> list[str]:
    """Everything past the burst: behaviours, dash, minions, absorb."""
    bits = []
    for b in tier.get("behaviours", []):
        if b["type"] == "homing":
            bits.append(f"homing {b['cone_deg']}° cone")
        elif b["type"] == "blast":
            bits.append(f"blast {b['radius_tiles']} tiles" + (" (splash only)" if b["blast_only"] else ""))
        elif b["type"] == "chain":
            bits.append(f"chains {b['bounces']}x")
        else:
            bits.append(b["type"])
    if tier.get("projectile", {}).get("pierce"):
        bits.append("pierces")
    if tier.get("dash"):
        bits.append(f"dash {tier['dash']['speed_px']} px/s for {tier['dash']['duration']}s")
    if tier.get("minion"):
        m = tier["minion"]
        bits.append(f"{m['count']} minions, {m['health']} hp, {m['lifetime']}s")
    if tier.get("absorb"):
        bits.append(f"absorbs {tier['absorb']}")
    return bits


def _grants(tier: dict) -> str:
    return ", ".join(f"{k} +{v}" for k, v in (tier.get("grants") or {}).items()) or "—"


def _amount_text(tier: dict) -> str:
    """The damage/heal formula as authored, with its value at base stats."""
    amount = tier.get("amount")
    if not amount:
        return "—"
    terms = [str(amount["base"])] if amount["base"] else []
    terms += [f"{v}×{k}" for k, v in amount.items() if k != "base" and v]
    if not terms:
        return "—"
    text = " + ".join(terms)
    total = _damage(tier)
    return f"{text} = **{round(total)}**" if len(terms) > 1 else f"**{text}**"


# --- Markdown ---------------------------------------------------------------

def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    return (
        ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
        + [""]
    )


def render_spells_md(data: dict) -> str:
    lines = [BEGIN, GEN_NOTE, ""]
    for cat in data["categories"]:
        members = [s for s in data["spells"] if s["category"] == cat["id"]]
        if not members:
            continue
        lines += [f"## {cat['name']}", "", cat["description"], ""]
        for sp in members:
            lines += [f"### {sp['name']}", "", sp["description"], ""]
            facts = [f"**Scaling:** {', '.join(sp['scaling'])}"]
            if sp["hold"] != "no":
                facts.append(f"**Hold:** {sp['hold']}")
            if sp["per_tier"]:
                facts.append(f"**Per tier:** {sp['per_tier']}")
            lines += [" · ".join(facts), ""]
            rows = []
            for t in sp["tiers"]:
                rows.append([
                    f"T{t['tier']}",
                    f"{t['cooldown']}s",
                    f"{t['cast_time']}s" if t["cast_time"] else "instant",
                    burst(t) or "—",
                    _amount_text(t),
                    f"{t['projectile']['range_tiles']}" if t.get("projectile") else "—",
                    _grants(t),
                ])
            lines += _table(
                ["Tier", "Cooldown", "Cast", "Burst", "Amount", "Range", "Grants"], rows
            )
            notes = sorted({e for t in sp["tiers"] for e in extras(t)})
            if notes:
                lines += [f"**Also:** {', '.join(notes)}.", ""]
    lines.append(END)
    return "\n".join(lines).rstrip() + "\n"


def _drops_text(enemy: dict) -> str:
    return ", ".join(
        f"**{d['spell']}{f' t{d['tier']}' if d['tier'] else ''}** ({round(d['chance'] * 100)}%)"
        for d in enemy["drops"]
    ) or "—"


def render_enemies_md(data: dict) -> str:
    lines = [BEGIN, GEN_NOTE, ""]
    for fam in data["families"]:
        lines += [f"## {fam['name']}", "", fam["enemies_intro"], ""]
        for eid in fam["roster"]:
            e = data["_by_enemy"][eid]
            suffix = "" if e["rarity"] == "common" else f" *({e['rarity']})*"
            lines += [f"### {e['name']}{suffix}", "", e["description"].rstrip("\n"), ""]
            lines += [f"**Art:** {e['art']}", ""]

            rows = [["Difficulty", f"{e['difficulty']} / 10"], ["HP", e["max_health"]]]
            if e.get("speed_px"):
                rows.append(["Speed", f"{e['speed_px']} px/s"])
            if e.get("probes"):
                rows.append(["Range", ", ".join(f"{k} {v}" for k, v in e["probes"].items())])
            for a in e["attacks"]:
                bits = [f"{a['cooldown']}s cd"] if a["cooldown"] else []
                bits += [b for b in [burst(a)] if b]
                if a.get("projectile"):
                    bits.append(f"{a['projectile']['range_tiles']} tiles range")
                bits += extras(a)
                dmg = f"**{a['amount']['base']}** dmg — " if (a.get("amount") or {}).get("base") else ""
                rows.append([a["name"], dmg + ", ".join(bits)])
            rows.append(["Drops", _drops_text(e)])
            lines += _table(["Stat", ""], rows)

            if e["notes"]:
                lines += [f"**Notes:** {e['notes']}", ""]
            lines.append("```mermaid")
            lines.append("stateDiagram-v2")
            lines.append(f"    [*] --> {e['fsm']['start']}")
            for t in e["fsm"]["transitions"]:
                edge = f"    {t['from']} --> {t['to']}"
                lines.append(edge + (f" : {t['when']}" if t.get("when") else ""))
            lines += ["```", ""]
    lines.append(END)
    return "\n".join(lines).rstrip() + "\n"


def render_biomes_md(data: dict) -> str:
    lines = [BEGIN, GEN_NOTE, ""]
    kit = ", ".join(f"**{k['spell']}**" for k in data["starter_kit"])
    lines += [f"Player spawns with: {kit}.", ""]
    lines += [
        "Notation: `Nx` count (a range prints `1-2x`), `+` means \"together in the room\", "
        "`-` separates the variations the generator may roll for that room (it picks one). "
        "Rooms are listed in placement order — difficulty tier, then id.",
        "",
    ]
    rooms_by_biome: dict[str, list] = {}
    for room in data["rooms"]:
        rooms_by_biome.setdefault(room["biome"], []).append(room)

    for fam in data["families"]:
        title = fam["name"] + (f" ({fam['tier_label']})" if fam["tier_label"] else "")
        lines += [f"## {title}", "", fam["intro"], ""]
        for bid in fam["biomes"]:
            b = next(x for x in data["biomes"] if x["id"] == bid)
            lines += [f"### {b['name']}", "", b["intro"], ""]
            rows = []
            for room in rooms_by_biome.get(bid, []):
                quota = (
                    f"{room['min_per_biome']}"
                    if room["min_per_biome"] == room["max_per_biome"]
                    else f"w{room['weight']}"
                )
                rows.append([
                    f"T{room['difficulty']}",
                    room["id"].removeprefix(f"{bid}_"),
                    room["generator"],
                    quota,
                    notation(room["variations"]),
                ])
            lines += _table(["Tier", "Room", "Shape", "Count", "Enemy group variations"], rows)

            if b["planned"]:
                planned = ", ".join(b["roster"])
                lines += [
                    f"Nothing spawns here yet — every room above carries an empty table. "
                    f"Planned roster: {planned}.",
                    "",
                ]

            if b["roster"]:
                lines += [f"#### {b['name']} drops", ""]
                lines += _table(
                    ["Enemy", "Items dropped"],
                    [
                        [
                            data["_by_enemy"][eid]["name"]
                            + ("" if data["_by_enemy"][eid]["rarity"] == "common"
                               else f" *({data['_by_enemy'][eid]['rarity']})*"),
                            _drops_text(data["_by_enemy"][eid]),
                        ]
                        for eid in b["roster"]
                    ],
                )
    lines.append(END)
    return "\n".join(lines).rstrip() + "\n"


def inject(md_path: Path, catalogue: str) -> str:
    """Splice `catalogue` between the GENERATED markers of an existing doc."""
    src = md_path.read_text()
    if BEGIN not in src or END not in src:
        raise SystemExit(
            f"{md_path} is missing the generated-catalogue markers ({BEGIN!r} / {END!r})."
        )
    head = src[: src.index(BEGIN)]
    tail = src[src.index(END) + len(END):].lstrip("\n")
    # Blank line before any hand-written tail (e.g. the "---" / "# ideas" section)
    # so a bare "---" under the END comment can't read as a setext heading.
    sep = "\n\n" if tail else "\n"
    return head + catalogue.rstrip("\n") + sep + tail


# --- HTML -------------------------------------------------------------------

def render_html(template_name: str) -> str:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES)),
        autoescape=select_autoescape(["html"]),
    )
    return env.get_template(template_name).render()


# --- driver -----------------------------------------------------------------

def build() -> tuple[dict[Path, str], list[str]]:
    design = {name: load(f"{name}.yaml") for name in ("spells", "enemies", "biomes")}
    game = extract.extract()

    errors = validate(design, game)
    if errors:
        return {}, errors

    data = join(design, game)
    public = {k: v for k, v in data.items() if not k.startswith("_")}
    blob = json.dumps(public, ensure_ascii=False, indent=1)

    spells_md, enemies_md, biomes_md = (DOCS / f"{n}.md" for n in ("spells", "enemies", "biomes"))
    outputs = {
        DOCS / "data.json": blob + "\n",
        # Assigned, not fetched: a page opened straight off disk has no origin to
        # fetch from, and the whole point is that these files just open.
        DOCS / "data.js": "window.MAGES = " + blob + ";\n",
        DOCS / "mages.css": (TEMPLATES / "mages.css").read_text(),
        DOCS / "mages.js": (TEMPLATES / "mages.js").read_text(),
        spells_md: inject(spells_md, render_spells_md(data)),
        enemies_md: inject(enemies_md, render_enemies_md(data)),
        biomes_md: inject(biomes_md, render_biomes_md(data)),
    }
    for name in ("spells", "spells_balance", "enemies", "biomes"):
        outputs[DOCS / f"{name}.html"] = render_html(f"{name}.html.j2")
    return outputs, []


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if anything is stale")
    args = ap.parse_args()

    outputs, errors = build()
    if errors:
        print(f"{len(errors)} problem(s) — the yaml and the game disagree:")
        for e in errors:
            print(f"  {e}")
        return 1

    if args.check:
        stale = sorted(
            str(path.relative_to(ROOT.parent))
            for path, content in outputs.items()
            if not path.exists() or path.read_text() != content
        )
        if stale:
            print("STALE (run design/tools/build.py):", ", ".join(stale))
            return 1
        print("up to date")
        return 0

    for path, content in outputs.items():
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
